apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pod
  template:
    metadata:
      name: postgres-pod
      labels:
        app: postgres-pod
    spec:
      containers:
        - name: postgres
          image: postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: ""
            - name: POSTGRES_PASSWORD
              value: ""
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
