apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
